# ~/.config/hypr/hyprlock.conf

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 4
    color = rgba(5, 5, 5, 0.9)
}

input-field {
    monitor =
    size = 250, 40
    outline_thickness = 1
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(208, 208, 208, 1.0)
    inner_color = rgba(18, 18, 18, 1.0)
    font_color = rgba(208, 208, 208, 1.0)
    fade_on_empty = false
    placeholder_text = <span font_family="JetBrains Mono" foreground="##8a8a8a">Password...</span>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
    rounding = 4
}

label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 1.0)
    font_size = 64
    font_family = JetBrains Mono Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = Syed Zeeshan Azhar
    color = rgba(138, 138, 138, 1.0)
    font_size = 14
    font_family = JetBrains Mono
    position = 0, 10
    halign = center
    valign = center
}
